name: spotify-mcp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip-tools
  - pip:
    - pre-commit
    - -e services/shared
    - -e services/api[dev]
    - -e services/collector[dev]
    - -e services/frontend[dev]

  - sqlalchemy